name: .NET Desktop CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
    
    # Silence Node.js 20 deprecation warnings by forcing actions to run on Node.js 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      Solution_Name: LibVideo2.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build the application
      run: msbuild $env:Solution_Name /t:Rebuild /p:Configuration=${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LibVideo-${{ matrix.configuration }}
        path: LibVideo\bin\${{ matrix.configuration }}\
